name: macOS 11

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'pango glib glib-networking gobject-introspection pkg-config jq' }}

on:
  push:
    branches:
      - swift52
  pull_request:
    branches:
      - swift52

jobs:
  # macOS tasks
  build-mac-big-sur-swift-latest:
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'

      - name: Print Swift version to confirm
        run: swift --version

      - name: Fetch dependencies for general repository
        run: brew install $MACOS_BREW

      - name: Checkout SwiftPango
        uses: actions/checkout@v2
        with:
          ref: swift52
          path: SwiftPango

      - name: Build Swift Wrappers
        run: |
          cd SwiftPango
          ./run-gir2swift.sh
          echo "GIR2SWIFT_PATH=${PWD}/checkouts/gir2swift/.build/release/gir2swift" >> $GITHUB_ENV
          cd ..

      - name: Build SwiftPango
        run: |
          cd SwiftPango
          swift build `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Test SwiftPango
        run: |
          cd SwiftPango
          swift test `./run-gir2swift.sh flags -noUpdate`
          cd ..

      - name: Remove unneeded files and archive artefacts
        run: | 
          cd SwiftPango
          swift package clean
          rm -rf .build/repositories
          cd ..
